name: Android CI

on:
  push:
    branches:
      - ci
  pull_request:
    branches:
      - ci

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Build and test
        run: |
          ./gradlew build
          ./gradlew test
